### ISSUE TITLE
fileType does not work for debian packages

### ISSUE THREAD

**Issue by omerozkan** [nebula-plugins/gradle-ospackage-plugin#74] opened 2015-01-07 12:53 UTC
Hello

For debian packages, there is a problem config files. In the debian packages there must be `conffiles` file in control.tar.gz for configuration files. But the plugin does not create `conffiles` for configured `fileType CONFIG | NOREPLACE`

Regards

**Comment by bmuschko** [comment] 2015-06-09 15:22
Would you be interested in working on a pull request for this?

**Comment by sghill** [comment] 2016-12-22 21:19
Closing as duplicate of #118

**Closed by sghill** 2016-12-22 21:19 UTC
