### ISSUE TITLE
Unsafe resolution of project configuration warning

### ISSUE THREAD

**Issue by kunickiaj** [nebula-plugins/gradle-ospackage-plugin#317] opened 2019-01-07 19:47 UTC
When using Gradle 5.1 with plugin version <= 6.1.1, I get the warning:

```
The configuration <subproject configuration name> was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project.  See https://docs.gradle.org/5.1/userguide/troubleshooting_dependency_resolution.html#configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0
```

I was originally receiving this warning when using the gradle distribution plugin, and making a reference such as:

`from <subproject>.configurations.runtimeClasspath` in the distribution CopySpec.
I was able to resolve this by instead defining a distribution in the subproject and replacing the above reference with: `with <subproject>.distributions.<distribution name>.contents`

However, when running the RPM task from the nebula plugin, I get the warning regardless of which CopySpec definition method I'm using.

Haven't yet looked into the plugin source, but perhaps someone else more familiar would know what the issue could be here and how to resolve it.

**Comment by rpalcolea** [comment] 2019-01-08 17:53
Hi @kunickiaj,

Can you provide a sample project with this?

With it, it would be easier for us to reproduce/debug and fix it

**Comment by rpalcolea** [comment] 2019-01-08 19:15
Just a heads up:

current master uses latest `nebula-test` (`7.1.7`) which checks for mutable project state warnings and deprecation warnings:

https://github.com/nebula-plugins/nebula-test/blob/master/src/main/groovy/nebula/test/BaseIntegrationSpec.groovy#L102
https://github.com/nebula-plugins/nebula-test/blob/master/src/main/groovy/nebula/test/BaseIntegrationSpec.groovy#L85

Here is a test to reproduce it -> https://github.com/nebula-plugins/nebula-test/blob/master/src/test/groovy/nebula/test/MutableProjectStateWarningCheckIntegrationSpec.groovy

With that said, all the integration tests on this project check for this and fail if a warning is present in the build output. 

The RPM integration test (https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginIntegrationTest.groovy) would fail if those warnings are present and that isn't the case -> https://travis-ci.org/nebula-plugins/gradle-ospackage-plugin/builds/476983618

This makes me think that either:

1) we are missing a test case (which could be a specific project setup)
2) somewhere in your project, you are accessing configurations this way and when you run the RPM tasks, you get the warning

**Comment by kunickiaj** [comment] 2019-01-08 20:19
Thanks for the info. Let me see if I can create a simpler setup for repro
and share.

**Comment by kunickiaj** [comment] 2019-01-09 19:12
Seems that I'm having this issue, even without the rpm plugin.
Created a repro repo (minus ospackage) here for the curious: https://github.com/kunickiaj/rpm-warn-repro

**Comment by rpalcolea** [comment] 2019-09-25 19:41
I think is because of this: https://github.com/kunickiaj/rpm-warn-repro/blob/master/build.gradle#L27

This is asking gradle to resolve the configurations when evaluating the project 

Closing this issue as it isn't ospackage related

**Closed by rpalcolea** 2019-09-25 19:41 UTC
