### ISSUE TITLE
config | noreplace not being set

### ISSUE THREAD

**Issue by camechis** [nebula-plugins/gradle-ospackage-plugin#56] opened 2014-10-07 18:19 UTC
I am attempting to build an RPM and marking certain files as config noreplace.  I have used this in the past with success, however, it now appears not to be working. 

```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "com.netflix.nebula:gradle-ospackage-plugin:1.12.7"
  }
}

apply plugin: "os-package"
version = '1.0'



ospackage {
    os      = LINUX
    arch    = X86_64
    release = 3
    version = project.version

    user    = 'root'
    packageName = 'example'
    permissionGroup = 'root'
    packageDescription = 'example proj'

    vendor  = 'foobar'
    url     = 'foobar.com'
    license = 'foo'

    from('config/testconf') {
        into '/opt/test/config'
        fileMode = 0644
        fileType = CONFIG | NOREPLACE
    }

    from('nonconfig/nonconfig') {
        into '/opt/test/not'
        fileMode = 0644
    }

}

task( type: Wrapper) {
   gradleVersion = '1.12'
}
```

Above is the example I have been using.  After installing the RPM i queried the DB using

```
sudo rpm -q --qf '[%{filenames}: %{fileflags}\n]' example
```

and get the following results

```
/opt/test: 0
/opt/test/config: 0
/opt/test/config/testconf: 0
/opt/test/not: 0
/opt/test/not/nonconfig: 0
```

I believe the value of 0 should be equal to 17 if I translated the rpmlib.h correctly for /opt/test/config/testconf

Any suggestions or glaring mistakes that I have made?

**Comment by bmuschko** [comment] 2015-03-20 15:01
@camechis Still interested?

**Comment by bmuschko** [comment] 2015-06-09 15:23
Is that the same issue as #74?

**Comment by bedge** [comment] 2015-08-21 05:47
Any update on this?
I found that I can get a single conffile declared using:
```
    configurationFile('/etc/nim/cmas.properties')
```
But not more than one. 
How does one use this to declare multiple conffiles?

It still ignores:
```
	from('src/etc/') {
        fileType CONFIG | NOREPLACE
		into '/etc/'
	}
```

**Comment by bedge** [comment] 2015-09-08 16:56
Finally stumbled across this combination that works. Apparently even creating a list of files for configurationFile doesn't work as it's inserted verbatim.
Here's what does work, currently:
```
ospackage {
    ....
	configurationFile = 
		"/etc/default/app-name.conf\n" +
	 	"/etc/app-name/app.properties"
```
Note one needs to include the explicit linefeed in between items.

I would argue that the plugin should expand any type of list into the conffile as one line per element.

If you do include a string array, it uses the array.toString verbatim, which includes square brackets, quoted strings etc.

**Comment by sghill** [comment] 2016-12-22 21:18
Closing as duplicate of #118

**Closed by sghill** 2016-12-22 21:18 UTC
