### ISSUE TITLE
Rpm task is never UP-TO-DATE when using 'os' and 'arch' properties

### ISSUE THREAD

**Issue by mark-vieira** [nebula-plugins/gradle-ospackage-plugin#82] opened 2015-02-21 16:56 UTC
In the 2.2 branch, when using the Rpm task along with setting the 'os' and 'arch' properties, the task runs on every execution because Gradle believes those properties have changed. Removing said properties causes incremental builds to work as expected.

**Comment by bmuschko** [comment] 2015-03-19 19:33
Would you mind sending us a pull request that reproduces the issue? We'll use that test as the base for verifying the fix.

**Comment by mark-vieira** [comment] 2015-03-26 23:53
Ben, I've submitted a [PR](https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/94) for this.

**Comment by mark-vieira** [comment] 2015-03-26 23:56
Ok, this test fails locally for me but seems to pass in CI. Not sure why that would be the case.

**Comment by quidryan** [comment] 2015-03-27 07:05
I merged the test, but found that it couldn't run on its own. The problem was that the fields weren't being assigned like this:

    apply plugin: 'rpm'
    
    task buildRpm(type: Rpm) {
        packageName = 'rpmIsUpToDate'
        arch = NOARCH
        os = LINUX
    }

Test passes for me. We might just have to keep an eye on this.

**Comment by mark-vieira** [comment] 2015-03-27 15:31
That is strange. The assignment operators should be optional in this case.

**Comment by bmuschko** [comment] 2015-04-20 20:12
@mark-vieira Can we close this issue?

**Comment by mark-vieira** [comment] 2015-04-21 16:07
Yep. I'll open another issue if I can figure out how to reproduce this consistently.

**Comment by bmuschko** [comment] 2015-04-21 16:17
Cool, thanks for the feedback!

**Closed by bmuschko** 2015-04-21 16:17 UTC
